config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :product_tsvs
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  include PgSearch::Model
  after_save :update_tsv
  has_one :product_tsv

  private

  def update_tsv
    if product_tsv.present?
      product_tsv.update(tsv: get_tsv)
    else
      ProductTsv.create(tsv: get_tsv, product: self)
    end
  end

  def get_tsv
    ActiveRecord::Base
        .connection
        .execute(
            "SELECT (to_tsvector('english', coalesce('#{title}', '')) ||
           to_tsvector('english', coalesce('#{description}', '')) ||
           to_tsvector('english', coalesce('#{country}', ''))) AS tsvector"
        )
        .first['tsvector']
  end
end

app/models/product_tsv.rb
class ProductTsv < ApplicationRecord
  include PgSearch::Model
  belongs_to :product

  # ID column is not taken into consideration when using the tsvector_column
  pg_search_scope :search,
                  against: :id,
                  using: {
                      tsearch: {
                          prefix: true,
                          dictionary: 'english',
                          tsvector_column: 'tsv'
                      }
                  }

  pg_search_scope :search_with_relevance,
                  associated_against: {
                      product: {
                          title: 'A',
                          description: 'B',
                          country: 'C',
                          tags: 'D'
                      }
                  },
                  using: {
                      tsearch: {
                          prefix: true
                      }
                  }

  scope :order_by_price, ->(order_type: 'ASC') {
    joins(:product)
        .order(price: order_type.to_sym)
  }

  scope :price_equal_to, ->(value) {
    joins(:product)
        .where('price = ?', value)
  }

  scope :price_less_than, ->(value) {
    joins(:product)
        .where('price < ?', value)
  }

  scope :price_higher_than, ->(value) {
    joins(:product)
        .where('price > ?', value)
  }

  scope :filter_by_country, ->(country_name) {
    joins(:product)
        .where('country = ?', country_name)
  }

  scope :countries, lambda {
    joins(:product)
        .pluck('products.country')
        .uniq << 'All'
  }

  def self.text_search(search_value, relevance: false)
    return all unless search_value.present?

    if relevance
      search_with_relevance(search_value)
    else
      search(search_value)
    end
  end

  def self.sort_types
    [
        %w[None none],
        %w[Relevance relevance],
        %w[Newest newest],
        %w[Lowest Price, lowest_price],
        %w[Highest Price, highest_price]
    ].freeze
  end

  def self.price_ranges
    [
        %w[None none],
        %w[Less than, less_than],
        %w[Equals to, equals_to],
        %w[Higher than, higher_than]
    ].freeze
  end

  private

  def associated_products_table_name(value)
    if value
      'products'
    else
      'products_product_tsvs'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @product_tsvs = ProductTsv
                        .order('RANDOM()')
                        .includes(:product)
                        .page(0)
                        .per(8)
    @countries = ProductTsv.countries
    @sort_types = ProductTsv.sort_types
    @price_ranges = ProductTsv.price_ranges
  end
end

app/controllers/product_tsvs_controller.rb
class ProductTsvsController < ApplicationController
  before_action :set_product_tsv, only: [:show, :edit, :update, :destroy]

  # GET /product_tsvs
  # GET /product_tsvs.json
  def index
    sleep(1)

    @product_tsv_searcher = ProductTsvs::ProductTsvSearcher.new(params: params)

    @product_tsvs = @product_tsv_searcher
                        .process
                        .page(params[:page])
                        .per(8)
  end

  # GET /product_tsvs/1
  # GET /product_tsvs/1.json
  def show
  end

  # GET /product_tsvs/new
  def new
    @product = ProductTsv.new
  end

  # GET /product_tsvs/1/edit
  def edit
  end

  # POST /product_tsvs
  # POST /product_tsvs.json
  def create
    @product = ProductTsv.new(product_tsv_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'ProductTsv was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_tsvs/1
  # PATCH/PUT /product_tsvs/1.json
  def update
    respond_to do |format|
      if @product.update(product_tsv_params)
        format.html { redirect_to @product, notice: 'ProductTsv was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_tsvs/1
  # DELETE /product_tsvs/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to product_tsvs_url, notice: 'ProductTsv was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product_tsv
    @product_tsv = ProductTsv.find(params[:id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :country, :tags, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/home/_search_form.html.erb
<%= form_tag(product_tsvs_path, method: :get, remote: true) do %>
  <div class="row">
    <div class="col-12 mb-2">
      <%= text_field_tag :search, '', class: 'form-control form-control-lg', placeholder: 'Search for a product...' %>
    </div>
    <%= button_tag 'Search', class: 'btn btn-block btn-lg btn-primary', id: 'search-button', hidden: '' %>
    <div class="col-md-12 mt-1">
      <p>
        <%= link_to 'More search options',
                    'javascript:;',
                    class: 'btn btn-sm btn-light',
                    data: {toggle: 'collapse'},
                    href: '#collapseExample',
                    role: 'button',
                    aria: {expanded: false, controls: 'collapseExample'} %>
      </p>
    </div>
  </div>

  <div class="collapse text-black-50" id="collapseExample">
    <div class="row">
      <div class="col-md-4">
        <h6>Price range</h6>
        <%= select_tag 'price_range', options_for_select(@price_ranges, @price_ranges.first), class: 'form-control form-control-sm' %>
        <%= text_field_tag :price, '', class: 'form-control form-control-sm mt-1', placeholder: 'Enter price...', type: 'number', step: '0.01' %>
      </div>
      <div class="col-md-4">
        <h6>Origin coutry</h6>
        <%= select_tag 'country', options_for_select(@countries, @countries.last), class: 'form-control form-control-sm' %>
      </div>
      <div class="col-md-4">
        <h6>Sort By</h6>
        <%= select_tag 'sort_by', options_for_select(@sort_types, @sort_types.first), class: 'form-control form-control-sm' %>
        <div class="mt-2">
          <%= link_to 'Clear Filters', 'javascript:;', onclick: 'clearSearchOptions()' %>
        </div>
      </div>
    </div>
  </div>
<% end %>

<script>
    function clearSearchOptions() {
        $('input[name=price]').val('');

        $('select[name=price_range]').val('none');

        $('select[name=country]').val('All');

        $('select[name=sort_by').val('none');

        $("#spinner-search").show();

        $('#search-button').click();
    }
</script>

app/views/home/index.html.erb
<header class="masthead text-white text-center mt-3">
  <div class="overlay"></div>
  <div class="container mb-6">
    <div class="row">
      <div class="col-lg-12">
        <%= render 'home/search_form' %>
      </div>
    </div>
  </div>

  <div id="products-div">
    <%= render 'product_tsvs/index', show_pagination: true, product_tsvs: @product_tsvs %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpocketChallenge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'partials/spinner' %>
    <%= yield %>
  </body>
</html>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-light bg-light static-top">
  <div class="container">
    <%= link_to 'Spocket Challenge', root_path, class: 'navbar-brand'  %>
    <%= link_to 'About', root_path, role: 'button', class: 'btn btn-primary'  %>
  </div>
</nav>

app/views/partials/_spinner.html.erb
<div class="spinner-border text-primary float-right mr-2" id="spinner-search" role="status" style="display: none;">
  <span class="sr-only">Loading...</span>
</div>

app/views/product_tsvs/_index.html.erb
<p id="notice"><%= notice %></p>

<!-- Page Content -->
<div class="container">
  <div class="row justify-content-center">
    <% product_tsvs.each do |product_tsv| %>
      <div class="col-xl-3 col-md-6 d-flex align-items-sm-stretch mb-4">
        <div class="card border-0 shadow">
          <img src="https://picsum.photos/seed/<%= rand(500) %>/300/150" class="loading card-img-top" alt="...">
          <div class="card-body text-center">
            <h6 class="card-title mb-0 text-black-50"><%= product_tsv.product.title %></h6>
            <div class="card-text text-black-50">
              <b>Description: </b>
              <%= product_tsv.product.description %>
            </div>
            <div class="card-text text-black-50">
              <b>Country: </b>
              <%= product_tsv.product.country %>
            </div>
            <div class="card-text text-black-50 font-weight-bold">Price: $<%= product_tsv.product.price %></div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="d-flex justify-content-center">
    <% if show_pagination %>
      <%= paginate product_tsvs, remote: true %>
    <% end %>
  </div>
  <!-- /.row -->
</div>
<!-- /.container -->

app/views/product_tsvs/index.js.erb
$("#products-div").html(
    "<%= j (render 'index', show_pagination: true, product_tsvs: @product_tsvs) %>"
);

function stopSpinner() {
    $("#spinner-search").hide();
}

stopSpinner();

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div class="field">
    <%= form.label :tags %>
    <%= form.text_field :tags %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_index.html.erb
<p id="notice"><%= notice %></p>

<!-- Page Content -->
<div class="container align-content-center">
  <div class="row">
    <% @products.each do |product| %>
      <div class="col-xl-3 col-md-6 d-flex align-items-sm-stretch mb-4">
        <div class="card border-0 shadow">
          <img src="https://picsum.photos/seed/<%= rand(500) %>/500/350" class="card-img-top" alt="...">
          <div class="card-body text-center">
            <h6 class="card-title mb-0 text-black-50"><%= product.title %></h6>
            <div class="card-text text-black-50"><%= product.description %></div>
            <div class="card-text text-black-50 font-weight-bold">Price: $<%= product.price %></div>
          </div>
        </div>
      </div>
    <% end %>
    <%= paginate @products, remote: true %>
  </div>
  <!-- /.row -->
</div>
<!-- /.container -->

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<!-- Page Content -->
<div class="container align-content-center">
  <div class="row">
    <% @products.each do |product| %>
      <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-0 shadow">
          <img src="https://picsum.photos/seed/<%= rand(500) %>/500/350" class="card-img-top" alt="...">
          <div class="card-body text-center">
            <h5 class="card-title mb-0"><%= product.title %></h5>
            <div class="card-text text-black-50"><%= product.description %></div>
          </div>
        </div>
      </div>
    <% end %>
    <%= paginate @products, remote: true %>
  </div>
  <!-- /.row -->
</div>
<!-- /.container -->

app/views/products/index.js.erb
$("#products-div").html(
    "<%= j (render 'index', products: @products) %>"
);

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Country:</strong>
  <%= @product.country %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @product.tags %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>